trigger:
- main
pr: none  # Disable PR triggers, can be adjusted as needed

pool:
  name: Default  # This should point to your self-hosted agent pool

steps:
- script: |
    # Update pip to the latest version
    pip3 install --upgrade pip

    # Install Ansible core version 2.15.12
    pip3 install ansible==2.15.12

    # Install Ansible Azure collection
    pip3 install ansible[azure]

    # Install additional required Azure SDK dependencies
    pip3 install msrest msrestazure azure-mgmt-resource
  displayName: 'Install Ansible and Azure dependencies'

- script: |
    # Run Ansible playbook to create Azure App Service
    ansible-playbook create-linux-app-svc2.yml
  displayName: 'Run Ansible Playbook'
  env:
    AZURE_SUBSCRIPTION_ID: 'df37ad58-72dd-4c55-aa45-70a1be1a1461'
    AZURE_CLIENT_ID: '8c92339a-b725-45ee-bad2-ddf1853970a5'
    AZURE_SECRET: $(AZURE_SECRET) 
    AZURE_TENANT: 'cc22f83f-24d0-4740-a762-37c892d89308'