trigger:
- main

pr: none  # Disable PR triggers, can be adjusted as needed

pool:
  name: Default  # This should point to your self-hosted agent pool

steps:
- bash: |
    # Ensure Homebrew is up to date
    brew update
    
    # Install Python3.12 if not already installed
    brew install python@3.12
    
    # Link the installed Python version
    brew link --overwrite python@3.12
    
    # Set up a virtual environment
    python3 -m venv ansible_env
    source ansible_env/bin/activate
    
    # Upgrade pip and install Ansible with Azure dependencies
    pip install --upgrade pip
    pip install "ansible==2.9.17"
    pip install ansible[azure]
  displayName: 'Install Ansible and Azure dependencies in virtual environment'
  
- bash: |
    source ansible_env/bin/activate
    # Run Ansible playbook to create Azure App Service
    ansible-playbook create-linux-app-svc2.yml
  displayName: 'Run Ansible Playbook'
  env:
    AZURE_SUBSCRIPTION_ID: 'df37ad58-72dd-4c55-aa45-70a1be1a1461'
    AZURE_CLIENT_ID: '8c92339a-b725-45ee-bad2-ddf1853970a5'
    AZURE_SECRET: '$(AZURE_SECRET)'  # Enclosed in quotes
    AZURE_TENANT: 'cc22f83f-24d0-4740-a762-37c892d89308'