trigger:
- main
pr: none  # Disable PR triggers, can be adjusted as needed

pool:
  name: Default  # This should point to your self-hosted agent pool

steps:
- bash: |
    # Update Homebrew and install Python3
    brew update
    brew install python3
    
    # Upgrade pip and install Ansible with Azure dependencies
    pip3 install --upgrade pip
    pip3 install "ansible==2.9.17"
    pip3 install ansible[azure]
  displayName: 'Install Ansible and Azure dependencies'

- script: |
    # Run Ansible playbook to create Azure App Service
    ansible-playbook create-linux-app-svc2.yml
  displayName: 'Run Ansible Playbook'
  env:
    AZURE_SUBSCRIPTION_ID: 'df37ad58-72dd-4c55-aa45-70a1be1a1461'
    AZURE_CLIENT_ID: '8c92339a-b725-45ee-bad2-ddf1853970a5'
    AZURE_SECRET: $(AZURE_SECRET) 
    AZURE_TENANT: 'cc22f83f-24d0-4740-a762-37c892d89308'