trigger:
- main
pr: none  # Disable PR triggers, can be adjusted as needed
pool:
  name: Default  # Specify the self-hosted agent pool name

steps:
- script: |
    # Install Ansible core version 2.15.12
    pip3 install "ansible==2.15.12"
  displayName: 'Install Ansible core'

- script: |
    # Install Ansible Azure collection
    ansible-galaxy collection install azure.azcollection
  displayName: 'Install Ansible Azure Collection'

- script: |
    # Run Ansible playbook to create Azure App Service
    ansible-playbook create-linux-app-svc2.yml
  displayName: 'Run Ansible Playbook'
  env:
    AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
    AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
    AZURE_SECRET: $(AZURE_SECRET) 
    AZURE_TENANT: $(AZURE_TENANT)

