trigger:
- main
pr: none  # Disable PR triggers, can be adjusted as needed

# Use self-hosted agent pool
pool:
  name: 'Default'  # Replace 'SelfHostedPool' with the actual name of your self-hosted agent pool

steps:
- script: |
    # Install Ansible
    pip3 install "ansible==10.1.0"
  displayName: 'Install Ansible'
  
- script: |
    # Install Ansible rm module
    pip3 install ansible[azure]
  displayName: 'Install Ansible rm module'
  
- script: |
    # Run Ansible playbook to create Azure App Service
    ansible-playbook create-linux-app-svc2.yml
  displayName: 'Run Ansible Playbook'
  env:
    AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
    AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
    AZURE_SECRET: $(AZURE_SECRET) 
    AZURE_TENANT: $(AZURE_TENANT)

